// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.4
// source: pyenv/proto/pyenv.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hashes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sha256 string `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
}

func (x *Hashes) Reset() {
	*x = Hashes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pyenv_proto_pyenv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hashes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hashes) ProtoMessage() {}

func (x *Hashes) ProtoReflect() protoreflect.Message {
	mi := &file_pyenv_proto_pyenv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hashes.ProtoReflect.Descriptor instead.
func (*Hashes) Descriptor() ([]byte, []int) {
	return file_pyenv_proto_pyenv_proto_rawDescGZIP(), []int{0}
}

func (x *Hashes) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

// Wheel represents a Python wheel package from pylock.toml
type Wheel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url    string  `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Path   string  `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Size   int64   `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Hashes *Hashes `protobuf:"bytes,5,opt,name=hashes,proto3" json:"hashes,omitempty"`
}

func (x *Wheel) Reset() {
	*x = Wheel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pyenv_proto_pyenv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wheel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wheel) ProtoMessage() {}

func (x *Wheel) ProtoReflect() protoreflect.Message {
	mi := &file_pyenv_proto_pyenv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wheel.ProtoReflect.Descriptor instead.
func (*Wheel) Descriptor() ([]byte, []int) {
	return file_pyenv_proto_pyenv_proto_rawDescGZIP(), []int{1}
}

func (x *Wheel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Wheel) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Wheel) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Wheel) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Wheel) GetHashes() *Hashes {
	if x != nil {
		return x.Hashes
	}
	return nil
}

// PythonVersion represents a supported Python runtime
type PythonVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version        string            `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	PythonPath     string            `protobuf:"bytes,2,opt,name=python_path,json=pythonPath,proto3" json:"python_path,omitempty"`
	SysTags        []string          `protobuf:"bytes,3,rep,name=sys_tags,json=sysTags,proto3" json:"sys_tags,omitempty"`
	EnvMarkers     map[string]string `protobuf:"bytes,4,rep,name=env_markers,json=envMarkers,proto3" json:"env_markers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DcontainerPath string            `protobuf:"bytes,5,opt,name=dcontainer_path,json=dcontainerPath,proto3" json:"dcontainer_path,omitempty"`
}

func (x *PythonVersion) Reset() {
	*x = PythonVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pyenv_proto_pyenv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PythonVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PythonVersion) ProtoMessage() {}

func (x *PythonVersion) ProtoReflect() protoreflect.Message {
	mi := &file_pyenv_proto_pyenv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PythonVersion.ProtoReflect.Descriptor instead.
func (*PythonVersion) Descriptor() ([]byte, []int) {
	return file_pyenv_proto_pyenv_proto_rawDescGZIP(), []int{2}
}

func (x *PythonVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PythonVersion) GetPythonPath() string {
	if x != nil {
		return x.PythonPath
	}
	return ""
}

func (x *PythonVersion) GetSysTags() []string {
	if x != nil {
		return x.SysTags
	}
	return nil
}

func (x *PythonVersion) GetEnvMarkers() map[string]string {
	if x != nil {
		return x.EnvMarkers
	}
	return nil
}

func (x *PythonVersion) GetDcontainerPath() string {
	if x != nil {
		return x.DcontainerPath
	}
	return ""
}

// InstallWheelsReq requests installation of multiple wheels and acquires locks on all of them.
// This is an atomic operation - either all locks are acquired (and missing wheels installed),
// or none are.
type InstallWheelsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wheels        []*Wheel `protobuf:"bytes,1,rep,name=wheels,proto3" json:"wheels,omitempty"`
	PythonVersion string   `protobuf:"bytes,2,opt,name=python_version,json=pythonVersion,proto3" json:"python_version,omitempty"` // e.g., "cpython3.11"
}

func (x *InstallWheelsReq) Reset() {
	*x = InstallWheelsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pyenv_proto_pyenv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallWheelsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallWheelsReq) ProtoMessage() {}

func (x *InstallWheelsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pyenv_proto_pyenv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallWheelsReq.ProtoReflect.Descriptor instead.
func (*InstallWheelsReq) Descriptor() ([]byte, []int) {
	return file_pyenv_proto_pyenv_proto_rawDescGZIP(), []int{3}
}

func (x *InstallWheelsReq) GetWheels() []*Wheel {
	if x != nil {
		return x.Wheels
	}
	return nil
}

func (x *InstallWheelsReq) GetPythonVersion() string {
	if x != nil {
		return x.PythonVersion
	}
	return ""
}

// InstallWheelsRep returns the installation result and lock handle.
// The lock_handle must be passed to ReleaseLocks to release the references.
type InstallWheelsRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstallPaths []string `protobuf:"bytes,1,rep,name=install_paths,json=installPaths,proto3" json:"install_paths,omitempty"` // Parallel to wheels in request
	LockHandle   uint64   `protobuf:"varint,2,opt,name=lock_handle,json=lockHandle,proto3" json:"lock_handle,omitempty"`      // Opaque handle for ReleaseLocks (0 = no handle)
	Error        string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                   // Empty on success
}

func (x *InstallWheelsRep) Reset() {
	*x = InstallWheelsRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pyenv_proto_pyenv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallWheelsRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallWheelsRep) ProtoMessage() {}

func (x *InstallWheelsRep) ProtoReflect() protoreflect.Message {
	mi := &file_pyenv_proto_pyenv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallWheelsRep.ProtoReflect.Descriptor instead.
func (*InstallWheelsRep) Descriptor() ([]byte, []int) {
	return file_pyenv_proto_pyenv_proto_rawDescGZIP(), []int{4}
}

func (x *InstallWheelsRep) GetInstallPaths() []string {
	if x != nil {
		return x.InstallPaths
	}
	return nil
}

func (x *InstallWheelsRep) GetLockHandle() uint64 {
	if x != nil {
		return x.LockHandle
	}
	return 0
}

func (x *InstallWheelsRep) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ReleaseLocksReq releases all locks associated with a lock handle.
type ReleaseLocksReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LockHandle uint64 `protobuf:"varint,1,opt,name=lock_handle,json=lockHandle,proto3" json:"lock_handle,omitempty"` // Handle returned by InstallWheels (must be > 0)
}

func (x *ReleaseLocksReq) Reset() {
	*x = ReleaseLocksReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pyenv_proto_pyenv_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseLocksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLocksReq) ProtoMessage() {}

func (x *ReleaseLocksReq) ProtoReflect() protoreflect.Message {
	mi := &file_pyenv_proto_pyenv_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLocksReq.ProtoReflect.Descriptor instead.
func (*ReleaseLocksReq) Descriptor() ([]byte, []int) {
	return file_pyenv_proto_pyenv_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseLocksReq) GetLockHandle() uint64 {
	if x != nil {
		return x.LockHandle
	}
	return 0
}

// ReleaseLocksRep returns the result of releasing locks.
type ReleaseLocksRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // Empty on success
}

func (x *ReleaseLocksRep) Reset() {
	*x = ReleaseLocksRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pyenv_proto_pyenv_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseLocksRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLocksRep) ProtoMessage() {}

func (x *ReleaseLocksRep) ProtoReflect() protoreflect.Message {
	mi := &file_pyenv_proto_pyenv_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLocksRep.ProtoReflect.Descriptor instead.
func (*ReleaseLocksRep) Descriptor() ([]byte, []int) {
	return file_pyenv_proto_pyenv_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseLocksRep) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pyenv_proto_pyenv_proto protoreflect.FileDescriptor

var file_pyenv_proto_pyenv_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x79, 0x65, 0x6e, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x79,
	0x65, 0x6e, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x06, 0x48, 0x61, 0x73,
	0x68, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x22, 0x76, 0x0a, 0x05, 0x57,
	0x68, 0x65, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x07, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x52, 0x06, 0x68, 0x61, 0x73,
	0x68, 0x65, 0x73, 0x22, 0x8e, 0x02, 0x0a, 0x0d, 0x50, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x79, 0x73, 0x5f, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x79, 0x73, 0x54, 0x61, 0x67, 0x73, 0x12, 0x3f, 0x0a, 0x0b, 0x65,
	0x6e, 0x76, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x50, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x2e, 0x45, 0x6e, 0x76, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x0a, 0x65, 0x6e, 0x76, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x12, 0x27, 0x0a, 0x0f,
	0x64, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x50, 0x61, 0x74, 0x68, 0x1a, 0x3d, 0x0a, 0x0f, 0x45, 0x6e, 0x76, 0x4d, 0x61, 0x72, 0x6b,
	0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x59, 0x0a, 0x10, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x57,
	0x68, 0x65, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x06, 0x77, 0x68, 0x65, 0x65,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x57, 0x68, 0x65, 0x65, 0x6c,
	0x52, 0x06, 0x77, 0x68, 0x65, 0x65, 0x6c, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x79, 0x74, 0x68,
	0x6f, 0x6e, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0x6e, 0x0a, 0x10, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x73,
	0x52, 0x65, 0x70, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x5f, 0x70,
	0x61, 0x74, 0x68, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6c, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x6b,
	0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6c,
	0x6f, 0x63, 0x6b, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x32, 0x0a, 0x0f, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x22, 0x27, 0x0a, 0x0f, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4c, 0x6f,
	0x63, 0x6b, 0x73, 0x52, 0x65, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x15, 0x5a, 0x13,
	0x73, 0x69, 0x67, 0x6d, 0x61, 0x6f, 0x73, 0x2f, 0x70, 0x79, 0x65, 0x6e, 0x76, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pyenv_proto_pyenv_proto_rawDescOnce sync.Once
	file_pyenv_proto_pyenv_proto_rawDescData = file_pyenv_proto_pyenv_proto_rawDesc
)

func file_pyenv_proto_pyenv_proto_rawDescGZIP() []byte {
	file_pyenv_proto_pyenv_proto_rawDescOnce.Do(func() {
		file_pyenv_proto_pyenv_proto_rawDescData = protoimpl.X.CompressGZIP(file_pyenv_proto_pyenv_proto_rawDescData)
	})
	return file_pyenv_proto_pyenv_proto_rawDescData
}

var file_pyenv_proto_pyenv_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pyenv_proto_pyenv_proto_goTypes = []interface{}{
	(*Hashes)(nil),           // 0: Hashes
	(*Wheel)(nil),            // 1: Wheel
	(*PythonVersion)(nil),    // 2: PythonVersion
	(*InstallWheelsReq)(nil), // 3: InstallWheelsReq
	(*InstallWheelsRep)(nil), // 4: InstallWheelsRep
	(*ReleaseLocksReq)(nil),  // 5: ReleaseLocksReq
	(*ReleaseLocksRep)(nil),  // 6: ReleaseLocksRep
	nil,                      // 7: PythonVersion.EnvMarkersEntry
}
var file_pyenv_proto_pyenv_proto_depIdxs = []int32{
	0, // 0: Wheel.hashes:type_name -> Hashes
	7, // 1: PythonVersion.env_markers:type_name -> PythonVersion.EnvMarkersEntry
	1, // 2: InstallWheelsReq.wheels:type_name -> Wheel
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pyenv_proto_pyenv_proto_init() }
func file_pyenv_proto_pyenv_proto_init() {
	if File_pyenv_proto_pyenv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pyenv_proto_pyenv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hashes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pyenv_proto_pyenv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wheel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pyenv_proto_pyenv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PythonVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pyenv_proto_pyenv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallWheelsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pyenv_proto_pyenv_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallWheelsRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pyenv_proto_pyenv_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseLocksReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pyenv_proto_pyenv_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseLocksRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pyenv_proto_pyenv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pyenv_proto_pyenv_proto_goTypes,
		DependencyIndexes: file_pyenv_proto_pyenv_proto_depIdxs,
		MessageInfos:      file_pyenv_proto_pyenv_proto_msgTypes,
	}.Build()
	File_pyenv_proto_pyenv_proto = out.File
	file_pyenv_proto_pyenv_proto_rawDesc = nil
	file_pyenv_proto_pyenv_proto_goTypes = nil
	file_pyenv_proto_pyenv_proto_depIdxs = nil
}
