#!/usr/bin/env python3
import os
import subprocess
from pathlib import Path
from textwrap import indent

script_dir = Path(__file__).resolve().parent
workspace_root = script_dir / ".." / ".."

def bazel_query(*query):
    if "BUILD_WORKSPACE_DIRECTORY" in os.environ:
        exe = "bazel"
    else:
        exe = "./build.sh"

    result = subprocess.run(
        [exe, "query"] + list(query),
        check=True,
        capture_output=True,
        text=True,
        cwd=workspace_root,
    )
    return sorted(result.stdout.strip().splitlines())

def user_targets():
    return (
        bazel_query("kind('go_binary', //cmd/user/...)") +
        bazel_query("kind('cc_binary', //cpp/user/...)") +
        [
            "//rs/spawn-latency",
        ]
    )

def kernel_targets():
    return (
        bazel_query("kind('go_binary', //cmd/kernel/...)") +
        [
            "//rs/uproc-trampoline",
        ]
    )

def wasm_targets():
    return (
        bazel_query("kind('rust_shared_library', //rs/wasm/...)")
    )

def main():
    user = indent('\n'.join(f'"{t}",' for t in user_targets()), ' ' * 8)
    kernel = indent('\n'.join(f'"{t}",' for t in kernel_targets()), ' ' * 8)
    wasm = indent('\n'.join(f'"{t}",' for t in wasm_targets()), ' ' * 8)

    build_content = f"""\
# DON'T EDIT THIS BUILD FILE BY HAND
# AUTOMATICALLY GENERATED BY /bin/genbuild.py

# gazelle:ignore

load("//tools/build_rules:copy_directory.bzl", "copy_directory")

filegroup(
    name = "user",
    srcs = [
{user}
    ],
)

filegroup(
    name = "kernel",
    srcs = [
{kernel}
    ],
)

filegroup(
    name = "wasm",
    srcs = [
{wasm}
    ],
)

filegroup(
    name = "linux",
    srcs = [
        "//cmd/linux/bootkernel:bootkernel",
    ],
)

filegroup(
    name = "npproxy",
    srcs = [
        "//cmd/npproxy/npproxyd:npproxyd",
    ],
)

copy_directory(
    name = "bin",
    out_dir = "bin",
    mappings = {{
        "/user": ":user",
        "/kernel": ":kernel",
        "/wasm": ":wasm",
        "/linux": ":linux",
        "/npproxy": ":npproxy",
    }},
    visibility = ["//bin:__pkg__"],
)
"""

    out = workspace_root / "bin" / "BUILD.bazel"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_content)

if __name__ == "__main__":
    main()
